import gleam/dict.{type Dict}
import gleam/option.{type Option}
import openai/types as shared

pub type Request {
  Request(
    model: shared.Model,
    input: Input,
    instructions: Option(String),
    temperature: Option(Float),
    stream: Option(Bool),
    tool_choice: Option(ToolChoice),
    tools: Option(List(Tools)),
  )
}

/// Text, image, or file inputs to the model, used to generate a response.
pub type Input {
  /// A text input to the model, equivalent to a text input with the user role.
  InputText(String)
  /// A list of one or many input items to the model, containing different content types.
  InputList(List(InputListItem))
}

/// A list of one or many input items to the model, containing different content types.
pub type InputListItem {
  /// A message input to the model with a role indicating instruction following hierarchy.
  /// Instructions given with the developer or system role take precedence over instructions given
  /// with the user role. Messages with the assistant role are presumed to have been generated by the
  /// model in previous interactions.
  InputListItemMessage(InputMessage)
  InputListItemReference(id: String)
  //Item(InputItem)
}

pub type InputMessage {
  /// A message input to the model with a role indicating instruction following hierarchy. Instructions
  /// given with the developer or system role take precedence over instructions given with the user role.
  /// Messages with the assistant role are presumed to have been generated by the model in previous interactions.
  InputMessage(
    /// The role of the message input. One of user, assistant, system, or developer
    role: String,
    /// Text, image, or audio input to the model, used to generate a response. Can also contain previous
    /// assistant responses.
    content: ContentInput,
    // status: Option(InputMessageStatus)
  )
}

pub type ContentInput {
  /// A text input to the model.
  ContentInputText(String)
  /// A list of one or many input items to the model, containing different content types.
  ContentInputList(List(ContentItem))
}

/// A list of one or many input items to the model, containing different content types.
pub type ContentItem {
  /// The text input to the model.
  ContentItemText(text: String)
  /// An image input to the model. Learn about image inputs.
  ContentItemImage(
    /// The detail level of the image to be sent to the model. One of high, low, or auto.
    /// Defaults to auto.
    detail: String,
    /// The ID of the file to be sent to the model.
    file_id: Option(String),
    /// The URL of the image to be sent to the model. A fully qualified URL or base64 encoded
    /// image in a data URL.
    image_url: Option(String),
  )
  /// A file input to the model.
  ContentItemFile(
    /// The content of the file to be sent to the model.
    file_data: Option(String),
    /// The ID of the file to be sent to the model.
    file_id: Option(String),
    /// The URL of the file to be sent to the model.
    file_url: Option(String),
    /// The name of the file to be sent to the model.
    filename: Option(String),
  )
}

/// The status of item. One of in_progress, completed, or incomplete. Populated when items are
/// returned via API.
pub type InputMessageStatus {
  InProgress
  Completed
  Incomplete
}

pub type Tools {
  WebSearch(
    /// Filters for the search.
    filters: Option(WebSearchFilters),
    /// High level guidance for the amount of context window space to use for the search.
    /// One of low, medium, or high. medium is the default.
    search_context_size: Option(SearchContextSize),
    user_location: Option(UserLocation),
  )
  Mcp(
    /// A label for this MCP server, used to identify it in tool calls.
    server_label: String,
    /// List of allowed tool names or a filter object.
    allowed_tools: Option(McpAllowedTools),
    /// An OAuth access token that can be used with a remote MCP server, either with a
    /// custom MCP server URL or a service connector. Your application must handle the OAuth
    /// authorization flow and provide the token here.
    authorization: Option(String),
    // TODO: Added supported connectors (https://platform.openai.com/docs/guides/tools-connectors-mcp)
    /// Identifier for service connectors, like those available in ChatGPT. One of server_url or
    /// connector_id must be provided. Learn more about service connectors here:
    /// https://platform.openai.com/docs/guides/tools-connectors-mcp
    connector_id: Option(String),
    /// Optional HTTP headers to send to the MCP server. Use for authentication or other purposes.
    headers: Option(Dict(String, String)),
    /// Specify which of the MCP server's tools require approval.
    require_approval: Option(McpToolApproval),
    /// Optional description of the MCP server, used to provide more context.
    server_description: Option(String),
    /// The URL for the MCP server. One of server_url or connector_id must be provided.
    server_url: Option(String),
  )
}

pub type McpToolApproval {
  /// Specify which of the MCP server's tools require approval. Can be always, never, or a filter
  /// object associated with tools that require approval.
  McpToolApprovalFilter(
    /// A filter object to specify which tools are allowed.
    always: Option(McpToolFilter),
    /// A filter object to specify which tools are allowed.
    never: Option(McpToolFilter),
  )
  /// Specify a single approval policy for all tools. One of always or never. When set to always,
  /// all tools will require approval. When set to never, all tools will not require approval.
  McpToolApprovalSetting(String)
}

pub type McpAllowedTools {
  /// A string array of allowed tools
  McpAllowedTools(List(String))
  /// A filter object to specify which tools are allowed.
  McpAllowedToolsFilter(McpToolFilter)
}

pub type McpToolFilter {
  McpToolFilter(
    /// Indicates whether or not a tool modifies data or is read-only. If an MCP server
    /// is annotated with readOnlyHint, it will match this filter.
    read_only: Option(Bool),
    /// List of allowed tool names.
    tool_names: Option(List(String)),
  )
}

pub type WebSearchFilters {
  WebSearchFilters(allowed_domains: Option(List(String)))
}

pub type SearchContextSize {
  SCSLow
  SCSMedium
  SCSHigh
}

pub type UserLocation {
  UserLocation(
    /// Free text input for the city of the user, e.g. San Francisco.
    city: Option(String),
    /// The two-letter ISO country code of the user, e.g. US.
    country: Option(String),
    /// Free text input for the region of the user, e.g. California.
    region: Option(String),
    /// The IANA timezone of the user, e.g. America/Los_Angeles.
    timezone: Option(String),
    /// The type of location approximation. Always approximate.
    type_: Option(String),
  )
}

pub type ToolChoice {
  /// The model will not call any tool and instead generates a message.
  None
  /// The model can pick between generating a message or calling one or more tools.
  Auto
  /// The model must call one or more tools.
  Required
  /// Search the contents of uploaded files when generating a response.
  FileSearch
  /// Include data from the internet in model response generation.
  WebSearchPreview
  /// Create agentic workflows that enable a model to control a computer interface.
  ComputerUsePreview
  /// Enable the model to call custom code that you define, giving it access to additional data and capabilities.
  Function(String)
}
