import gleam/option.{type Option}
import openai/types as shared

pub type Request {
  Request(
    model: shared.Model,
    input: Input,
    instructions: Option(String),
    temperature: Option(Float),
    stream: Option(Bool),
    tool_choice: Option(ToolChoice),
    tools: Option(List(Tools)),
  )
}

/// Text, image, or file inputs to the model, used to generate a response.
pub type Input {
  /// A text input to the model, equivalent to a text input with the user role.
  InputText(String)
  /// A list of one or many input items to the model, containing different content types.
  InputList(List(InputListItem))
}

/// A list of one or many input items to the model, containing different content types.
pub type InputListItem {
  /// A message input to the model with a role indicating instruction following hierarchy.
  /// Instructions given with the developer or system role take precedence over instructions given
  /// with the user role. Messages with the assistant role are presumed to have been generated by the
  /// model in previous interactions.
  InputListItemMessage(InputMessage)
  InputListItemReference(id: String)
  //Item(InputItem)
}

pub type InputMessage {
  /// A message input to the model with a role indicating instruction following hierarchy. Instructions
  /// given with the developer or system role take precedence over instructions given with the user role.
  /// Messages with the assistant role are presumed to have been generated by the model in previous interactions.
  InputMessage(
    /// The role of the message input. One of user, assistant, system, or developer
    role: String,
    /// Text, image, or audio input to the model, used to generate a response. Can also contain previous
    /// assistant responses.
    content: ContentInput,
    // status: Option(InputMessageStatus)
  )
}

pub type ContentInput {
  /// A text input to the model.
  ContentInputText(String)
  /// A list of one or many input items to the model, containing different content types.
  ContentInputList(List(ContentItem))
}

/// A list of one or many input items to the model, containing different content types.
pub type ContentItem {
  /// The text input to the model.
  ContentItemText(text: String)
  /// An image input to the model. Learn about image inputs.
  ContentItemImage(
    /// The detail level of the image to be sent to the model. One of high, low, or auto.
    /// Defaults to auto.
    detail: String,
    /// The ID of the file to be sent to the model.
    file_id: Option(String),
    /// The URL of the image to be sent to the model. A fully qualified URL or base64 encoded
    /// image in a data URL.
    image_url: Option(String),
  )
  /// A file input to the model.
  ContentItemFile(
    /// The content of the file to be sent to the model.
    file_data: Option(String),
    /// The ID of the file to be sent to the model.
    file_id: Option(String),
    /// The URL of the file to be sent to the model.
    file_url: Option(String),
    /// The name of the file to be sent to the model.
    filename: Option(String),
  )
}

/// The status of item. One of in_progress, completed, or incomplete. Populated when items are
/// returned via API.
pub type InputMessageStatus {
  InProgress
  Completed
  Incomplete
}

pub type Tools {
  WebSearch(
    /// Filters for the search.
    filters: Option(WebSearchFilters),
    /// High level guidance for the amount of context window space to use for the search.
    /// One of low, medium, or high. medium is the default.
    search_context_size: Option(SearchContextSize),
    user_location: Option(UserLocation),
  )
}

pub type WebSearchFilters {
  WebSearchFilters(allowed_domains: Option(List(String)))
}

pub type SearchContextSize {
  SCSLow
  SCSMedium
  SCSHigh
}

pub type UserLocation {
  UserLocation(
    /// Free text input for the city of the user, e.g. San Francisco.
    city: Option(String),
    /// The two-letter ISO country code of the user, e.g. US.
    country: Option(String),
    /// Free text input for the region of the user, e.g. California.
    region: Option(String),
    /// The IANA timezone of the user, e.g. America/Los_Angeles.
    timezone: Option(String),
    /// The type of location approximation. Always approximate.
    type_: Option(String),
  )
}

pub type ToolChoice {
  /// The model will not call any tool and instead generates a message.
  None
  /// The model can pick between generating a message or calling one or more tools.
  Auto
  /// The model must call one or more tools.
  Required
  /// Search the contents of uploaded files when generating a response.
  FileSearch
  /// Include data from the internet in model response generation.
  WebSearchPreview
  /// Create agentic workflows that enable a model to control a computer interface.
  ComputerUsePreview
  /// Enable the model to call custom code that you define, giving it access to additional data and capabilities.
  Function(String)
}
