import gleam/dict
import gleam/dynamic/decode.{type Decoder}
import gleam/int
import gleam/json.{type Json}
import gleam/list
import gleam/option.{type Option, None, Some}
import openai/types/helpers
import openai/types/responses/compaction
import openai/types/responses/content
import openai/types/responses/message
import openai/types/responses/reasoning
import openai/types/responses/tool
import openai/types/responses/tool_choice
import openai/types/responses/tools/apply_patch
import openai/types/responses/tools/code_interpreter
import openai/types/responses/tools/computer
import openai/types/responses/tools/custom
import openai/types/responses/tools/file_search
import openai/types/responses/tools/function
import openai/types/responses/tools/image_generation
import openai/types/responses/tools/mcp
import openai/types/responses/tools/shell
import openai/types/responses/tools/web_search
import openai/types/responses/tools/web_search_preview

pub type Status {
  InProgress
  Completed
  Incomplete
  Failed
  Cancelled
  Queued
}

/// Text, image, or file inputs to the model, used to generate a response.
pub type InputOutputParam {
  /// A text input to the model, equivalent to a text input with the user role
  Text(String)
  /// A list of one or many input items to the model, containing different content types.
  Items(List(InputOutput))
}

pub fn encode_io_param(input: InputOutputParam) {
  case input {
    Text(text) -> json.string(text)
    Items(items) -> json.array(items, fn(item) { encode_io_item(item) })
  }
}

pub type InputOutput {
  EasyInputMessage(message.EasyInputMessage)
  /// A message input to the model with a role indicating instruction
  /// following hierarchy. Instructions given with the developer or system
  /// role take precedence over instructions given with the user role.
  MessageItem(message.Message)
  /// An output message from the model.
  ResponseOutputMessageItem(message.ResponseOutputMessage)
  /// The results of a file search tool call.
  FileSearchCallItem(file_search.FileSearchCall)
  /// A tool call to a computer use tool.
  ComputerCallItem(computer.ComputerCallDef)
  /// The output of a computer tool call.
  ComputerCallOutputItem(computer.ComputerCallOutputDef)
  /// The results of a web search tool.
  WebSearchCallItem(web_search.WebSearchCall)
  /// A tool call to run a function.
  FunctionCallItem(function.FunctionCall)
  FunctionCallOutputItem(function.FunctionCallOutput)
  // TODO Write these functions.
  // ToolSearchCall(tool_search.ToolSearchCall)
  // ToolSearchOutput(tool_search.ToolSearchOutput)
  /// A description of the chain of thought used by a /
  /// reasoning model while generating a response. Be sure
  /// to include these items in your input to the
  /// Responses API for subsequent turns of a conversation
  /// if you are manually managing context.
  ReasoningItem(reasoning.ReasoningDef)
  //
  // A description of the chain of thought used by a reasoning model while /
  // generating a response. Be sure to include these items in your input to
  // the Responses API for subsequent turns of a conversation if you are
  // manually managing context.
  ReasoningOutputItem(reasoning.ReasoningOutputDef)
  /// A compaction item generated by the v1/responses/compact API.
  CompactionItem(compaction.Compaction)
  /// An image generation request made by the model.
  ImageGenerationCallItem(image_generation.ImageGenerationCall)
  /// A tool call to run code.
  CodeInterpreterCallItem(code_interpreter.CodeInterpreterCall)
  /// A tool call to run a command on the local shell.
  LocalShellCallItem(shell.LocalShellCall)
  /// The output of a local shell tool call.
  LocalShellCallOutputItem(shell.LocalShellCallOutput)
  /// A tool representing a request to execute one or more shell commands.
  ShellCallItem(shell.ShellCall)
  /// The streamed output items emitted by a shell tool call.
  ShellCallOutputItem(shell.ShellCallOutput)
  /// A tool call representing a request to create, delete, or update files
  /// using diff patches.
  ApplyPatchCallItem(apply_patch.ApplyPatchCall)
  /// The streamed output emitted by an apply patch tool call.
  ApplyPatchCallOutputItem(apply_patch.ApplyPatchCallOutput)
  /// A list of tools available on an MCP server.
  McpListToolsItem(mcp.McpListTools)
  /// A request for human approval of a tool invocation.
  McpApprovalRequestItem(mcp.McpApprovalRequest)
  /// A response to an MCP approval request.
  McpApprovalResponseItem(mcp.McpApprovalResponse)
  /// An invocation of a tool on an MCP server.
  McpCallItem(mcp.McpCall)
  /// The output of a custom tool call from your code, being sent back to the
  /// model.
  CustomToolCallOutputItem(custom.CustomToolCallOutput)
  /// A call to a custom tool created by the model.
  CustomToolCallItem(custom.CustomToolCall)
  ItemReferenceItem(ItemReferenceBody)
}

fn encode_io_item(io_item: InputOutput) -> Json {
  // echo io_item
  // TODO Fill in the rest oio_item these input items.
  case io_item {
    EasyInputMessage(message) -> message.encode_easy_input_message(message)
    MessageItem(message) -> message.encode_message(message)
    ResponseOutputMessageItem(output_message) ->
      message.encode_response_output_message(output_message)
    ReasoningOutputItem(output) -> reasoning.encode_reasoning_output(output)
    FunctionCallItem(call) -> function.encode_function_call(call)
    FunctionCallOutputItem(call_output) ->
      function.encode_function_call_output(call_output)
    WebSearchCallItem(call) -> web_search.encode_web_search_call(call)
    ShellCallItem(call) -> shell.encode_shell_call(call)
    ShellCallOutputItem(call_output) ->
      shell.encode_shell_call_output(call_output)
    _ -> panic as "response.encode_input_item"
  }
}

pub type ItemReferenceBody {
  ItemReferenceBody(
    // type: "item_reference",
    /// The ID of the item to reference.
    id: String,
  )
}

pub type Conversation {
  Conversation(
    /// The unique ID of the conversation that this response was associated
    /// with.
    id: String,
  )
}

pub type ConversationParam(id) {
  /// The unique ID of the conversation.
  ConversationId(id)
  /// The conversation that this response belongs to.
  Object(Conversation)
}

pub type ConversationContext {
  ContinuePreviousResponse(String)
  ContinueConversation(ConversationParam(String))
}

pub type Includable {
  FileSearchCallResults
  WebSearchCallResults
  WebSearchCallActionSources
  MessageInputImageImageUrl
  ComputerCallOutputOutputImageUrl
  CodeInterpreterCallOutputs
  MessageOutputTextLogprobs
}

pub type ResponsePromptVariables(string) {
  String(string)
  Content(content.Content)
  Custom(Json)
}

pub type Prompt {
  Prompt(id: String, variables: Option(ResponsePromptVariables(String)))
}

pub type PromptCacheRetention {
  InMemory
  Hours24
}

pub type ServiceTier {
  ServiceTierAuto
  Default
  Flex
  Scale
  Priority
}

pub type StreamOptions {
  /// When true, stream obfuscation will be enabled. Stream obfuscation adds
  /// random characters to an obfuscation field on streaming delta events to
  /// normalize payload sizes as a mitigation to certain side-channel attacks.
  /// These obfuscation fields are included by default, but add a small amount
  /// of overhead to the data stream. You can set include_obfuscation to false
  /// to optimize for bandwidth if you trust the network links between your
  /// application and the OpenAI API.
  StreamOptions(include_obfuscation: Bool)
}

fn encode_conversation(conversation: Conversation) -> Json {
  json.object([#("id", json.string(conversation.id))])
}

fn encode_conversation_param(
  conversation_param: ConversationParam(String),
) -> Json {
  case conversation_param {
    ConversationId(id) -> json.string(id)
    Object(conversation) -> encode_conversation(conversation)
  }
}

fn encode_conversation_context(
  conversation_context: Option(ConversationContext),
) -> List(#(String, Json)) {
  case conversation_context {
    Some(ContinuePreviousResponse(id)) -> [
      #("previous_response_id", json.string(id)),
    ]

    Some(ContinueConversation(conversation)) -> [
      #("conversation", encode_conversation_param(conversation)),
    ]

    None -> []
  }
}

fn encode_includable(includable: Includable) -> Json {
  case includable {
    FileSearchCallResults -> "file_search_call.results"
    WebSearchCallResults -> "web_search_call.results"
    WebSearchCallActionSources -> "web_search_call.action.sources"
    MessageInputImageImageUrl -> "message.input_image.image_url"
    ComputerCallOutputOutputImageUrl -> "computer_call_output.output_image_url"
    CodeInterpreterCallOutputs -> "code_interpreter_call.outputs"
    MessageOutputTextLogprobs -> "message.output_text.logprobs"
  }
  |> json.string
}

fn encode_response_prompt_variables(
  response_prompt_variables: ResponsePromptVariables(String),
) -> Json {
  case response_prompt_variables {
    String(value) -> json.string(value)
    Content(content) -> content.encode_content(content)
    Custom(value) -> value
  }
}

fn encode_prompt(prompt: Prompt) -> Json {
  [
    #("id", json.string(prompt.id)),
  ]
  |> helpers.encode_option(
    "variables",
    prompt.variables,
    encode_response_prompt_variables,
  )
  |> json.object
}

fn encode_prompt_cache_retention(
  prompt_cache_retention: PromptCacheRetention,
) -> Json {
  case prompt_cache_retention {
    InMemory -> "in_memory"
    Hours24 -> "24h"
  }
  |> json.string
}

fn encode_service_tier(service_tier: ServiceTier) -> Json {
  case service_tier {
    ServiceTierAuto -> "auto"
    Default -> "default"
    Flex -> "flex"
    Scale -> "scale"
    Priority -> "priority"
  }
  |> json.string
}

fn encode_stream_options(stream_options: StreamOptions) -> Json {
  json.object([
    #("include_obfuscation", json.bool(stream_options.include_obfuscation)),
  ])
}

fn encode_verbosity_value(verbosity: Verbosity) -> Json {
  let _ = verbosity
  panic as "encode_verbosity_value: unsupported value"
}

fn encode_text_response_format_configuration(
  text_response_format_configuration: TextResponseFormatConfiguration,
) -> Json {
  case text_response_format_configuration {
    ResponseFormatText -> json.object([#("type", json.string("text"))])
    ResponseFormatJSONSchemaConfig(name:, schema:) ->
      json.object([
        #("type", json.string("json_schema")),
        #("name", json.string(name)),
        #("schema", schema),
      ])
    ResponseFormatJSONObject ->
      json.object([#("type", json.string("json_object"))])
  }
}

fn encode_text_param(text_param: TextParam) -> Json {
  helpers.encode_option(
    [],
    "verbosity",
    text_param.verbosity,
    encode_verbosity_value,
  )
  |> helpers.encode_option(
    "format",
    text_param.format,
    encode_text_response_format_configuration,
  )
  |> json.object
}

fn encode_truncation_value(truncation: Truncation) -> Json {
  case truncation {
    Auto -> "auto"
    Disabled -> "disabled"
  }
  |> json.string
}

fn encode_metadata(metadata: List(#(String, String))) -> Json {
  json.object(
    list.map(metadata, fn(entry) { #(entry.0, json.string(entry.1)) }),
  )
}

pub type Verbosity {
  Low
  Medium
  High
}

pub type TextResponseFormatConfiguration {
  /// type "text"
  ResponseFormatText
  ResponseFormatJSONSchemaConfig(
    /// The name of the response format. Must be a-z, A-Z, 0-9, or contain
    /// underscores and dashes, with a maximum length of 64.
    name: String,
    /// The schema for the response format, described as a JSON Schema object.
    schema: Json,
    // The type of response format being defined. Always json_schema.
    // type: "json_schema"
  )
  /// type "json_object"
  ResponseFormatJSONObject
}

fn decode_text_response_format_configuration() -> Decoder(
  TextResponseFormatConfiguration,
) {
  use type_ <- decode.field("type", decode.string)
  case type_ {
    "text" -> decode.success(ResponseFormatText)
    "json_object" -> decode.success(ResponseFormatJSONObject)
    "json_schema" -> {
      use name <- decode.field("name", decode.string)
      use _schema <- decode.field("schema", decode.dynamic)
      decode.success(ResponseFormatJSONSchemaConfig(name:, schema: json.null()))
    }
    _ -> panic as type_
  }
}

pub type TextParam {
  TextParam(
    /// An object specifying the format that the model must output.
    format: Option(TextResponseFormatConfiguration),
    /// Constrains the verbosity of the model's response. Lower values will
    /// result in more concise responses, while higher values will result in
    /// more verbose responses.
    verbosity: Option(Verbosity),
  )
}

pub fn new_text_param() -> TextParam {
  TextParam(format: None, verbosity: None)
}

pub fn text_format(
  text_param: TextParam,
  format: TextResponseFormatConfiguration,
) -> TextParam {
  TextParam(..text_param, format: Some(format))
}

pub fn text_verbosity(text_param: TextParam, verbosity: Verbosity) -> TextParam {
  TextParam(..text_param, verbosity: Some(verbosity))
}

pub type TextConfig {
  TextConfig(
    /// An object specifying the format that the model must output.
    format: Option(TextResponseFormatConfiguration),
    /// Constrains the verbosity of the model's response.
    verbosity: Option(Verbosity),
  )
}

fn decode_verbosity() -> Decoder(Verbosity) {
  decode.string
  |> decode.map(fn(verbosity) {
    case verbosity {
      "low" -> Low
      "medium" -> Medium
      "high" -> High
      _ -> panic as verbosity
    }
  })
}

pub fn decode_text_config() -> Decoder(TextConfig) {
  use format <- decode.field(
    "format",
    decode.optional(decode_text_response_format_configuration()),
  )
  use verbosity <- decode.field(
    "verbosity",
    decode.optional(decode_verbosity()),
  )
  decode.success(TextConfig(format:, verbosity:))
}

pub type Truncation {
  Auto
  Disabled
}

pub type CreateResponse {
  CreateResponse(
    /// Whether to run the model in the background
    background: Option(Bool),
    /// Context management configuration for this request.
    context_management: Option(compaction.ContextManagement),
    /// Continue a previous response or continue within a specific conversation.
    conversation_context: Option(ConversationContext),
    /// Specify additional output data to include in the model response.
    include: Option(List(Includable)),
    /// Text, image, or file inputs to the model, used to generate a response
    input: InputOutputParam,
    /// A system (or developer) message inserted into the model's context.
    instructions: Option(String),
    /// When using along with previous_response_id, the instructions from a
    /// previous response will not be carried over to the next response. This
    /// makes it simple to swap out system (or developer) messages in new
    /// responses.
    max_output_tokens: Option(Int),
    /// The maximum number of total calls to built-in tools that can be
    /// processed in a response. This maximum number applies across all built
    /// in tool calls, not per individual tool. Any further attempts to call
    /// a tool by the model will be ignored.
    max_tool_calls: Option(Int),
    /// Set of 16 key-value pairs that can be attached to an object. This can
    /// be useful for storing additional information about the object in a
    /// structured format, and querying for objects via API or the dashboard.
    /// Keys are strings with a maximum length of 64 characters. Values are
    /// strings with a maximum length of 512 characters.
    metadata: Option(List(#(String, String))),
    /// The model to use for generating a response.
    model: String,
    /// Whether to allow the model to run tool calls in parallel.
    parallel_tool_calls: Option(Bool),
    /// The unique ID of the previous response to the model. Use this to
    /// create multi-turn conversations. Learn more about conversation state.
    /// Cannot be used in conjunction with conversation.
    prompt: Option(Prompt),
    /// Used by OpenAI to cache responses for similar requests to optimize
    /// your cache hit rates. Replaces the user field.
    prompt_cache_key: Option(String),
    /// The retention policy for the prompt cache.
    prompt_cache_retention: Option(PromptCacheRetention),
    /// Configuration for reasoning models.
    reasoning: Option(reasoning.ReasoningDef),
    /// A stable identifier used to help detect users of your application /
    /// that may be violating OpenAI's usage policies. The IDs should be a
    /// string that uniquely identifies each user, with a maximum length of
    /// 64 characters. We recommend hashing their username or email address,
    /// in order to avoid sending us any identifying information.
    safety_identifier: Option(String),
    /// Specifies the processing type used for serving the request.
    service_tier: Option(ServiceTier),
    /// Whether to store the generated model response for later retrieval via
    /// API.
    store: Option(Bool),
    /// If set to true, the model response data will be streamed to the
    /// client as it is generated using server-sent events.
    stream: Option(Bool),
    /// Additional configuration for streaming responses.
    stream_options: Option(StreamOptions),
    /// What sampling temperature to use, between 0 and 2.
    temperature: Option(Float),
    /// Configuration options for a text response from the model. Can be plain
    /// text or structured JSON data. Learn more
    text: Option(TextParam),
    /// How the model should select which tool (or tools) to use when
    /// generating a response. See the tools Param
    ///eter to see how to specify
    /// which tools the model can call.
    tool_choice: Option(tool_choice.Param),
    /// An array of tools the model may call while generating a response. You
    /// can specify which tool to use by setting the tool_choice Param
    ///eter.
    tools: Option(List(tool.Tool)),
    /// An integer between 0 and 20 specifying the number of most likely
    /// tokens to return at each token position, each with an associated log
    /// probability. minimum0 maximum20
    top_logprobs: Option(Int),
    /// An alternative to sampling with temperature, called nucleus sampling,
    /// where the model considers the results of the tokens with top_p
    /// probability mass. So 0.1 means only the tokens comprising the top 10%
    /// probability mass are considered.
    /// We generally recommend altering this or temperature but not both.
    /// minimum0 maximum1
    top_p: Option(Float),
    /// The truncation strategy to use for the model response.
    /// auto: If the input to this Response exceeds the model's context
    /// window size, the model will truncate the response to fit the context
    /// window by dropping items from the beginning of the conversation.
    /// disabled (default): If the input size will exceed the context window
    /// size for a model, the request will fail with a 400 error.
    truncation: Option(Truncation),
  )
}

pub fn encode_create_response(create_response: CreateResponse) -> Json {
  helpers.encode_option([], "background", create_response.background, json.bool)
  |> helpers.encode_option(
    "context_management",
    create_response.context_management,
    compaction.encode_context_management,
  )
  |> helpers.encode_option_list(
    "include",
    create_response.include,
    encode_includable,
  )
  |> list.prepend(#("input", encode_io_param(create_response.input)))
  |> helpers.encode_option(
    "instructions",
    create_response.instructions,
    json.string,
  )
  |> helpers.encode_option(
    "max_output_tokens",
    create_response.max_output_tokens,
    json.int,
  )
  |> helpers.encode_option(
    "max_tool_calls",
    create_response.max_tool_calls,
    json.int,
  )
  |> helpers.encode_option(
    "metadata",
    create_response.metadata,
    encode_metadata,
  )
  |> list.prepend(#("model", json.string(create_response.model)))
  |> helpers.encode_option(
    "parallel_tool_calls",
    create_response.parallel_tool_calls,
    json.bool,
  )
  |> helpers.encode_option("prompt", create_response.prompt, encode_prompt)
  |> helpers.encode_option(
    "prompt_cache_key",
    create_response.prompt_cache_key,
    json.string,
  )
  |> helpers.encode_option(
    "prompt_cache_retention",
    create_response.prompt_cache_retention,
    encode_prompt_cache_retention,
  )
  |> helpers.encode_option(
    "reasoning",
    create_response.reasoning,
    reasoning.encode_reasoning,
  )
  |> helpers.encode_option(
    "safety_identifier",
    create_response.safety_identifier,
    json.string,
  )
  |> helpers.encode_option(
    "service_tier",
    create_response.service_tier,
    encode_service_tier,
  )
  |> helpers.encode_option("store", create_response.store, json.bool)
  |> helpers.encode_option("stream", create_response.stream, json.bool)
  |> helpers.encode_option(
    "stream_options",
    create_response.stream_options,
    encode_stream_options,
  )
  |> helpers.encode_option(
    "temperature",
    create_response.temperature,
    json.float,
  )
  |> helpers.encode_option("text", create_response.text, encode_text_param)
  |> helpers.encode_option(
    "tool_choice",
    create_response.tool_choice,
    tool_choice.encode_param,
  )
  |> helpers.encode_option_list(
    "tools",
    create_response.tools,
    tool.encode_tool,
  )
  |> helpers.encode_option(
    "top_logprobs",
    create_response.top_logprobs,
    json.int,
  )
  |> helpers.encode_option("top_p", create_response.top_p, json.float)
  |> helpers.encode_option(
    "truncation",
    create_response.truncation,
    encode_truncation_value,
  )
  |> fn(object) {
    list.append(
      encode_conversation_context(create_response.conversation_context),
      object,
    )
  }
  |> json.object
}

pub type Error {
  Error(code: String, message: String)
}

pub type Reason {
  MaxOutputTokens
  ContentFilter
}

pub type IncompleteDetails {
  IncompleteDetails(
    /// The reason why the response is incomplete.
    reason: Reason,
  )
}

pub type Billing {
  Billing(
    /// The entity billed for the response.
    payer: String,
  )
}

pub type Instructions {
  /// A text input to the model, equivalent to a text input with the developer role.
  InstructionsText(String)
  InstructionsItems(List(InputOutput))
}

pub type Usage {
  Usage(
    /// The number of input tokens.
    input_tokens: Int,
    /// A detailed breakdown of the input tokens.
    input_tokens_details: InputTokensDetails,
    /// The number of output tokens.
    output_tokens: Int,
    /// A detailed breakdown of the output tokens.
    output_tokens_details: OutputTokensDetails,
    /// The total number of tokens used.
    total_tokens: Int,
  )
}

pub type InputTokensDetails {
  InputTokensDetails(
    /// The number of cached input tokens.
    cached_tokens: Int,
  )
}

pub type OutputTokensDetails {
  OutputTokensDetails(
    /// The number of reasoning tokens in the output.
    reasoning_tokens: Int,
  )
}

pub type Response {
  Response(
    /// Unique identifier for this Response.
    id: String,
    /// Unix timestamp (in seconds) of when this Response was created.
    created_at: Int,
    // An error object returned when the model fails to generate a Response.
    error: Option(Error),
    /// Details about why the response is incomplete.
    incomplete_details: Option(IncompleteDetails),
    /// A system (or developer) message inserted into the model's context.
    /// When using along with previous_response_id, the
    /// instructions from a previous response will not be carried over to the
    /// next response. This makes it simple to swap out system (or developer)
    /// messages in new responses.
    instructions: Option(Instructions),
    /// Set of 16 key-value pairs that can be attached to an object. This can
    /// be useful for storing additional information about the object in a
    /// structured format, and querying for objects via API or the dashboard.
    /// Keys are strings with a maximum length of 64 characters. Values are
    /// strings with a maximum length of 512 characters.
    metadata: Option(List(#(String, String))),
    /// Model ID used to generate the response, like gpt-4o or o3. OpenAI
    /// offers a wide range of models with different
    /// capabilities, performance characteristics, and price points. Refer to
    /// the model guide to browse and compare available models.
    model: String,
    /// The object type of this resource - always set to response.
    object: String,
    /// An array of content items generated by the model. The length and
    /// order of items in the output array is dependent on the
    /// model's response. Rather than accessing the first item in the output
    /// array and assuming it's an assistant message with
    /// the content generated by the model, you might consider using the
    /// output_text property where supported in SDKs.
    output: List(InputOutput),
    /// Whether to allow the model to run tool calls in parallel.
    parallel_tool_calls: Bool,
    /// What sampling temperature to use, between 0 and 2. Higher values like
    /// 0.8 will make the output more random, while
    /// lower values like 0.2 will make it more focused and deterministic. We
    /// generally recommend altering this or top_p but not both.
    temperature: Float,
    /// How the model should select which tool (or tools) to use when
    /// generating a response.
    tool_choice: tool_choice.Param,
    /// An array of tools the model may call while generating a response. You
    /// can specify which tool to use by setting the tool_choice Param
    ///eter.
    tools: List(tool.Tool),
    /// An alternative to sampling with temperature, called nucleus sampling,
    /// where the model considers the results of the tokens
    /// with top_p probability mass. So 0.1 means only the tokens comprising
    /// the top 10% probability mass are considered.
    /// We generally recommend altering this or temperature but not both.
    /// gpt-5 and o-series models only
    top_p: Float,
    /// Whether to run the model response in the background.
    background: Bool,
    /// Unix timestamp (in seconds) of when this Response was completed. Only
    /// present when the status is completed.
    completed_at: Option(Float),
    /// The conversation that this response belonged to. Input items and
    /// output items from this response were automatically added to this
    /// conversation.
    conversation: Option(Conversation),
    /// An upper bound for the number of tokens that can be generated for a
    /// response, including visible output tokens and reasoning tokens.
    max_output_tokens: Option(Int),
    /// The status of the response generation. One of completed, failed,
    /// in_progress, cancelled, queued, or incomplete.
    /// The maximum number of total calls to built-in tools that can be
    /// processed in a response. This maximum number applies across all built-
    /// in tool calls, not per individual tool. Any further attempts to call a
    /// tool by the model will be ignored.
    max_tool_calls: Option(Int),
    /// SDK-only convenience property that contains the aggregated text output
    /// from all output_text items in the output array, if any are present.
    /// Supported in the Python and JavaScript SDKs.
    output_text: Option(String),
    /// The unique ID of the previous response to the model. Use this to
    /// create multi-turn conversations.
    previous_response_id: Option(String),
    /// Reference to a prompt template and its variables.
    prompt: Option(Prompt),
    /// Used by OpenAI to cache responses for similar requests to optimize
    /// your cache hit rates. Replaces the user field.
    prompt_cache_key: Option(String),
    /// The retention policy for the prompt cache. Set to 24h to enable
    /// extended prompt caching, which keeps cached prefixes active for longer
    /// up to a maximum of 24 hours
    prompt_cache_retention: Option(String),
    /// gpt-5 and o-series models only
    reasoning: reasoning.ReasoningDef,
    /// A stable identifier used to help detect users of your application that
    /// may be violating OpenAI's usage policies. The IDs should be a string
    /// that uniquely identifies each user. We recommend hashing their
    /// username or email address, in order to avoid sending us any
    /// identifying information. Learn more.
    safety_identifier: Option(String),
    /// Specifies the processing type used for serving the request.
    service_tier: String,
    /// The status of the response generation. One of completed, failed,
    /// in_progress, cancelled, queued, or incomplete.
    status: Status,
    /// Configuration options for a text response from the model. Can be plain
    /// text or structured JSON data.
    text: Option(TextResponseFormatConfiguration),
    /// An integer between 0 and 20 specifying the number of most likely
    /// tokens to return at each token position, each with an associated log
    /// probability.
    top_logprobs: Int,
    /// The truncation strategy to use for the model response.
    truncation: String,
    /// Billing details for this response.
    billing: Billing,
    /// Whether the response is stored for later retrieval.
    store: Bool,
    /// Represents token usage details including input tokens, output tokens,
    /// a breakdown of output tokens, and the total tokens used.
    usage: Option(Usage),
  )
}

/// Decodes a response ID and its output items.
/// Useful for tool calls
pub fn decode_id_output() -> Decoder(#(String, List(InputOutput))) {
  use id <- decode.field("id", decode.string)
  use output <- decode.field("output", decode.list(decode_io_item()))
  decode.success(#(id, output))
}

fn decode_error() -> Decoder(Error) {
  use code <- decode.field("code", decode.string)
  use message <- decode.field("message", decode.string)
  decode.success(Error(code:, message:))
}

fn decode_reason() -> Decoder(Reason) {
  decode.string
  |> decode.map(fn(reason) {
    case reason {
      "max_output_tokens" -> MaxOutputTokens
      "content_filter" -> ContentFilter
      _ -> panic as reason
    }
  })
}

fn decode_incomplete_details() -> Decoder(IncompleteDetails) {
  use reason <- decode.field("reason", decode_reason())
  decode.success(IncompleteDetails(reason:))
}

fn decode_io_item() -> Decoder(InputOutput) {
  use type_ <- decode.field("type", decode.string)
  case type_ {
    "message" ->
      message.decode_response_output_message()
      |> decode.map(ResponseOutputMessageItem)
    "web_search_call" ->
      web_search.decode_web_search_call()
      |> decode.map(WebSearchCallItem)
    "compaction" ->
      compaction.decode_compaction()
      |> decode.map(CompactionItem)
    "mcp_list_tools" ->
      mcp.decode_mcp_list_tools()
      |> decode.map(McpListToolsItem)
    "mcp_approval_request" ->
      mcp.decode_mcp_approval_request() |> decode.map(McpApprovalRequestItem)
    "mcp_call" -> mcp.decode_mcp_call() |> decode.map(McpCallItem)
    "function_call" ->
      function.decode_function_call() |> decode.map(FunctionCallItem)
    "shell_call" -> shell.decode_shell_call() |> decode.map(ShellCallItem)
    "shell_call_output" ->
      shell.decode_shell_call_output() |> decode.map(ShellCallOutputItem)
    "reasoning" ->
      reasoning.decode_reasoning_output() |> decode.map(ReasoningOutputItem)
    _ -> panic as type_
  }
}

fn decode_instructions() -> Decoder(Instructions) {
  decode.one_of(decode.string |> decode.map(InstructionsText), or: [
    decode.list(decode_io_item()) |> decode.map(InstructionsItems),
  ])
}

fn decode_metadata() -> Decoder(Option(List(#(String, String)))) {
  decode.optional(decode.dict(decode.string, decode.string))
  |> decode.map(fn(entries) { option.map(entries, dict.to_list) })
}

fn decode_conversation() -> Decoder(Conversation) {
  use id <- decode.field("id", decode.string)
  decode.success(Conversation(id:))
}

fn decode_prompt_variables() -> Decoder(ResponsePromptVariables(String)) {
  decode.one_of(decode.string |> decode.map(String), or: [
    decode.dynamic |> decode.map(fn(_) { Custom(json.null()) }),
  ])
}

fn decode_prompt() -> Decoder(Prompt) {
  use id <- decode.field("id", decode.string)
  use variables <- decode.field(
    "variables",
    decode.optional(decode_prompt_variables()),
  )
  decode.success(Prompt(id:, variables:))
}

// fn decode_reasoning() -> Decoder(reasoning.Reasoning) {
//   use effort <- decode.field("effort", decode.optional(decode.string))
//   use summary <- decode.field("summary", decode.optional(decode.string))
//   decode.success(
//     reasoning.Reasoning(
//       effort: case effort {
//         Some(t) -> Some(reasoning.decode_effort(t))
//         None -> None
//       },
//       summary: case summary {
//         Some(t) -> Some(reasoning.decode_summary(t))
//         None -> None
//       },
//     ),
//   )
// }

fn decode_response_status() -> Decoder(Status) {
  decode.string
  |> decode.map(fn(status) {
    case status {
      "queued" -> Queued
      "cancelled" -> Cancelled
      "completed" -> Completed
      "failed" -> Failed
      "in_progress" -> InProgress
      "incomplete" -> Incomplete
      _ -> panic as status
    }
  })
}

fn decode_float_like() -> Decoder(Float) {
  decode.one_of(decode.float, or: [decode.int |> decode.map(int.to_float)])
}

fn decode_text() -> Decoder(Option(TextResponseFormatConfiguration)) {
  use format <- decode.optional_field(
    "format",
    None,
    decode.optional(decode_text_response_format_configuration()),
  )
  decode.success(format)
}

fn decode_billing() -> Decoder(Billing) {
  use payer <- decode.field("payer", decode.string)
  decode.success(Billing(payer:))
}

fn decode_input_tokens_details() -> Decoder(InputTokensDetails) {
  use cached_tokens <- decode.field("cached_tokens", decode.int)
  decode.success(InputTokensDetails(cached_tokens:))
}

fn decode_output_tokens_details() -> Decoder(OutputTokensDetails) {
  use reasoning_tokens <- decode.field("reasoning_tokens", decode.int)
  decode.success(OutputTokensDetails(reasoning_tokens:))
}

fn decode_usage() -> Decoder(Usage) {
  use input_tokens <- decode.field("input_tokens", decode.int)
  use input_tokens_details <- decode.field(
    "input_tokens_details",
    decode_input_tokens_details(),
  )
  use output_tokens <- decode.field("output_tokens", decode.int)
  use output_tokens_details <- decode.field(
    "output_tokens_details",
    decode_output_tokens_details(),
  )
  use total_tokens <- decode.field("total_tokens", decode.int)
  decode.success(Usage(
    input_tokens:,
    input_tokens_details:,
    output_tokens:,
    output_tokens_details:,
    total_tokens:,
  ))
}

fn decode_tool() -> Decoder(tool.Tool) {
  use type_ <- decode.field("type", decode.string)
  case type_ {
    "function" -> function.decode_function() |> decode.map(tool.FunctionTool)
    "computer" -> computer.decode_computer() |> decode.map(tool.ComputerTool)
    "computer_use_preview" ->
      computer.decode_computer_use_preview()
      |> decode.map(tool.ComputerUsePreviewTool)
    "web_search" ->
      web_search.decode_web_search() |> decode.map(tool.WebSearchTool)
    "web_search_preview" ->
      web_search_preview.decode_web_search_preview()
      |> decode.map(tool.WebSearchPreviewTool)
    "mcp" -> mcp.decode_mcp() |> decode.map(tool.McpTool)
    "shell" -> shell.decode_shell() |> decode.map(tool.ShellTool)
    "local_shell" ->
      shell.decode_local_shell() |> decode.map(tool.LocalShellTool)
    "apply_patch" -> decode.success(tool.ApplyPatchTool)
    _ -> panic as type_
  }
}

pub fn decode_response() -> Decoder(Response) {
  // echo "decode_response"
  use id <- decode.field("id", decode.string)
  use created_at <- decode.field("created_at", decode.int)
  use error <- decode.field("error", decode.optional(decode_error()))
  use incomplete_details <- decode.field(
    "incomplete_details",
    decode.optional(decode_incomplete_details()),
  )
  use instructions <- decode.field(
    "instructions",
    decode.optional(decode_instructions()),
  )
  use metadata <- decode.field("metadata", decode_metadata())
  use model <- decode.field("model", decode.string)
  use object <- decode.field("object", decode.string)
  use output <- decode.field("output", decode.list(decode_io_item()))
  use parallel_tool_calls <- decode.field("parallel_tool_calls", decode.bool)
  use temperature <- decode.field("temperature", decode.float)
  use tool_choice <- decode.field(
    "tool_choice",
    tool_choice.decode_tool_choice_param(),
  )
  use tools <- decode.field("tools", decode.list(decode_tool()))
  use top_p <- decode.field("top_p", decode.float)
  use background <- decode.field("background", decode.bool)
  use completed_at <- decode.optional_field(
    "completed_at",
    None,
    decode.optional(decode_float_like()),
  )
  use conversation <- decode.optional_field(
    "conversation",
    None,
    decode.optional(decode_conversation()),
  )
  use max_output_tokens <- decode.field(
    "max_output_tokens",
    decode.optional(decode.int),
  )
  use max_tool_calls <- decode.field(
    "max_tool_calls",
    decode.optional(decode.int),
  )
  use output_text <- decode.optional_field(
    "output_text",
    None,
    decode.optional(decode.string),
  )
  use previous_response_id <- decode.field(
    "previous_response_id",
    decode.optional(decode.string),
  )
  use prompt <- decode.optional_field(
    "prompt",
    None,
    decode.optional(decode_prompt()),
  )
  use prompt_cache_key <- decode.field(
    "prompt_cache_key",
    decode.optional(decode.string),
  )
  use prompt_cache_retention <- decode.field(
    "prompt_cache_retention",
    decode.optional(decode.string),
  )
  use reasoning <- decode.field("reasoning", reasoning.decode_reasoning())
  use safety_identifier <- decode.field(
    "safety_identifier",
    decode.optional(decode.string),
  )
  use service_tier <- decode.field("service_tier", decode.string)
  use status <- decode.field("status", decode_response_status())
  use text <- decode.field("text", decode_text())
  use top_logprobs <- decode.field("top_logprobs", decode.int)
  use truncation <- decode.field("truncation", decode.string)
  use billing <- decode.field("billing", decode_billing())
  use store <- decode.field("store", decode.bool)
  use usage <- decode.field("usage", decode.optional(decode_usage()))
  decode.success(Response(
    id:,
    created_at:,
    error:,
    incomplete_details:,
    instructions:,
    metadata:,
    model:,
    object:,
    output:,
    parallel_tool_calls:,
    temperature:,
    tool_choice:,
    tools:,
    top_p:,
    background:,
    completed_at:,
    conversation:,
    max_output_tokens:,
    max_tool_calls:,
    output_text:,
    previous_response_id:,
    prompt:,
    prompt_cache_key:,
    prompt_cache_retention:,
    reasoning:,
    safety_identifier:,
    service_tier:,
    status:,
    text:,
    top_logprobs:,
    truncation:,
    billing:,
    store:,
    usage:,
  ))
}
