import gleam/json.{type Json}
import gleam/option.{type Option}
import openai/types/helpers
import openai/types/responses/network_policy

pub type CodeInterpreterCall {
  CodeInterpreterCall(
    /// The unique ID of the code interpreter tool call.
    id: String,
    /// The code to run, or null if not available.
    code: String,
    /// The ID of the container used to run the code.
    container_id: String,
    /// The outputs generated by the code interpreter.
    outputs: List(Output),
    /// The status of the code interpreter tool call.
    status: Status,
    // type: "code_interpreter_call"
  )
}

pub fn encode_code_interpreter_call(call: CodeInterpreterCall) -> Json {
  json.object([
    #("type", json.string("code_interpreter_call")),
    #("id", json.string(call.id)),
    #("code", json.string(call.code)),
    #("container_id", json.string(call.container_id)),
    #("outputs", json.array(call.outputs, encode_output)),
    #("status", encode_status(call.status)),
  ])
}

pub type Output {
  Output(
    /// The logs output from the code interpreter.
    logs: Logs,
    /// The image output from the code interpreter.
    image: Image,
  )
}

pub type Logs {
  Logs(
    /// The logs output from the code interpreter.
    logs: String,
    // type: "logs"
  )
}

pub type Image {
  Image(
    // type: "image"
    url: String,
  )
}

fn encode_output(output: Output) -> Json {
  json.object([
    #("logs", encode_logs(output.logs)),
    #("image", encode_image(output.image)),
  ])
}

fn encode_logs(logs: Logs) -> Json {
  json.object([
    #("type", json.string("logs")),
    #("logs", json.string(logs.logs)),
  ])
}

fn encode_image(image: Image) -> Json {
  json.object([
    #("type", json.string("image")),
    #("url", json.string(image.url)),
  ])
}

pub type Status {
  InProgress
  Completed
  Incomplete
  Interpreting
}

fn encode_status(status: Status) -> Json {
  case status {
    InProgress -> "in_progress"
    Completed -> "completed"
    Incomplete -> "incomplete"
    Interpreting -> "interpreting"
  }
  |> json.string
}

pub type CodeInterpreter {
  /// The code interpreter container. Can be a container ID or an object that
  /// specifies uploaded file IDs to make available to your code, along with an
  /// optional memory_limit setting.
  ///
  /// Accepts one of the following:
  /// UnionMember0 = string
  /// The container ID.
  CodeInterpreter(container: Container)
}

pub fn encode_code_interpreter(interpreter: CodeInterpreter) -> Json {
  json.object([
    #("type", json.string("code_interpreter")),
    #("container", encode_container(interpreter.container)),
  ])
}

pub type Container {
  ContainerAuto(Auto)
  ID(String)
}

fn encode_container(container: Container) -> Json {
  case container {
    ContainerAuto(auto_) -> encode_auto(auto_)
    ID(id) -> json.string(id)
  }
}

pub type Auto {
  Auto(
    /// Uploaded file IDs to make available to the code interpreter.
    file_ids: Option(List(String)),
    /// The memory limit for the container, in megabytes.
    memory_limit: Option(Int),
    /// The network policy applied to the container.
    network_policy: network_policy.NetworkPolicy,
  )
}
fn encode_auto(auto_: Auto) -> Json {
  [
    #("type", json.string("container_auto")),
    #(
      "network_policy",
      network_policy.encode_network_policy(auto_.network_policy),
    ),
  ]
  |> helpers.encode_option("memory_limit", auto_.memory_limit, json.int)
  |> helpers.encode_option_list("file_ids", auto_.file_ids, json.string)
  |> json.object
}
