import gleam/json.{type Json}
import gleam/option.{type Option}
import openai/types/helpers
import openai/types/responses/content.{type Content}

pub type CustomToolCallOutput {
  CustomToolCallOutput(
    /// An identifier used to map this custom tool call to a tool call output.
    call_id: String,
    // type: "custom_tool_call_output"
    /// The unique ID of the custom tool call output in the OpenAI platform.
    id: Option(String),
    /// The output returned for the custom tool call.
    output: Output,
  )
}

pub fn encode_custom_tool_call_output(
  custom_tool_call_output: CustomToolCallOutput,
) -> Json {
  [
    #("call_id", json.string(custom_tool_call_output.call_id)),
    #("output", encode_output(custom_tool_call_output.output)),
    #("type", json.string("custom_tool_call_output")),
  ]
  |> helpers.encode_option("id", custom_tool_call_output.id, json.string)
  |> json.object
}

pub type Output {
  OutputText(String)
  InputContent(List(Content))
}

fn encode_output(output: Output) -> Json {
  case output {
    OutputText(text) -> json.string(text)
    InputContent(content) -> json.array(content, content.encode_content)
  }
}

pub type CustomToolCall {
  CustomToolCall(
    /// An identifier used to map this custom tool call to a tool call output.
    call_id: String,
    /// The input for the custom tool call generated by the model.
    input: String,
    /// The name of the custom tool being called.
    name: String,
    // type: "custom_tool_call"
    /// The unique ID of the custom tool call in the OpenAI platform.
    id: Option(String),
    /// The namespace of the custom tool call.
    namespace: Option(String),
  )
}

pub fn encode_custom_tool_call(custom_tool_call: CustomToolCall) -> Json {
  [
    #("call_id", json.string(custom_tool_call.call_id)),
    #("name", json.string(custom_tool_call.name)),
    #("type", json.string("custom_tool_call")),
  ]
  |> helpers.encode_option("id", custom_tool_call.id, json.string)
  |> helpers.encode_option("namespace", custom_tool_call.namespace, json.string)
  |> json.object
}

pub type Custom {
  Custom(
    /// The name of the custom tool, used to identify it in tool calls.
    name: String,
    // type: "custom"
    /// Optional description of the custom tool, used to provide more context.
    description: Option(String),
    /// The input format for the custom tool. Default is unconstrained text.
    format: Option(CustomToolInputFormat),
  )
}

pub fn encode_custom(custom: Custom) -> Json {
  [
    #("type", json.string("custom")),
    #("name", json.string(custom.name)),
  ]
  |> helpers.encode_option(
    "format",
    custom.format,
    encode_custom_tool_input_format,
  )
  |> helpers.encode_option("description", custom.description, json.string)
  |> json.object
}

pub type CustomToolInputFormat {
  // type: "text"
  Text
  Grammer(Grammar)
}

fn encode_custom_tool_input_format(
  custom_tool_input_format: CustomToolInputFormat,
) -> Json {
  case custom_tool_input_format {
    Text -> json.object([#("type", json.string("text"))])
    Grammer(grammar) -> encode_grammar(grammar)
  }
}

pub type Grammar {
  Grammar(
    /// The grammar definition.
    definition: String,
    /// The syntax of the grammar definition. One of lark or regex.
    syntax: GrammarSyntax,
    // type: "grammar"
  )
}

fn encode_grammar(grammar: Grammar) -> Json {
  json.object([
    #("type", json.string("grammar")),
    #("definition", json.string(grammar.definition)),
    #("syntax", encode_grammar_syntax(grammar.syntax)),
  ])
}

pub type GrammarSyntax {
  Lark
  Regex
}

fn encode_grammar_syntax(grammar_syntax: GrammarSyntax) -> Json {
  case grammar_syntax {
    Lark -> json.string("lark")
    Regex -> json.string("regex")
  }
}
