import gleam/dynamic/decode.{type Decoder}
import gleam/json.{type Json}
import gleam/option.{type Option, None, Some}
import openai/types/helpers
import openai/types/responses/content

pub type Status {
  InProgress
  Completed
  Incomplete
}

fn encode_status(status: Status) -> Json {
  case status {
    InProgress -> "in_progress"
    Completed -> "completed"
    Incomplete -> "incomplete"
  }
  |> json.string
}

fn decode_status() -> Decoder(Status) {
  decode.string
  |> decode.map(fn(status) {
    case status {
      "in_progress" -> InProgress
      "completed" -> Completed
      "incomplete" -> Incomplete
      _ -> panic as status
    }
  })
}

pub type FunctionCall {
  FunctionCall(
    /// The name of the function to run.
    name: String,
    /// A JSON string of the arguments to pass to the function.
    arguments: String,
    /// The unique ID of the function tool call generated by the model.
    call_id: String,
    // type: "function_call"
    id: Option(String),
    /// The status of the item. One of in_progress, completed, or incomplete.
    status: Option(Status),
    /// The namespace of the function tool call.
    namespace: Option(String),
  )
}

pub fn encode_function_call(function_call: FunctionCall) -> Json {
  [
    #("type", json.string("function_call")),
    #("name", json.string(function_call.name)),
    #("arguments", json.string(function_call.arguments)),
    #("call_id", json.string(function_call.call_id)),
  ]
  |> helpers.encode_option("id", function_call.id, json.string)
  |> helpers.encode_option("namespace", function_call.namespace, json.string)
  |> helpers.encode_option("status", function_call.status, encode_status)
  |> json.object
}

pub fn decode_function_call() -> Decoder(FunctionCall) {
  use name <- decode.field("name", decode.string)
  use call_id <- decode.field("call_id", decode.string)
  use arguments <- decode.field("arguments", decode.string)
  use id <- decode.field("id", decode.optional(decode.string))
  use namespace <- decode.optional_field(
    "namespace",
    None,
    decode.optional(decode.string),
  )
  use status <- decode.optional_field(
    "status",
    None,
    decode.optional(decode_status()),
  )
  decode.success(FunctionCall(
    arguments:,
    call_id:,
    id:,
    status:,
    name:,
    namespace:,
  ))
}

/// The output of a function tool call.
pub type FunctionCallOutput {
  FunctionCallOutput(
    // type: function_call_output
    /// The unique ID of the function tool call generated by the model.
    call_id: String,
    /// The output of the function tool call.
    output: Output,
    /// The unique ID of the function tool call output. Populated when this item is returned via API.
    id: Option(String),
    /// The status of the item. One of in_progress, completed, or incomplete.
    status: Option(Status),
  )
}

pub fn encode_function_call_output(
  function_call_output: FunctionCallOutput,
) -> Json {
  [
    #("type", json.string("function_call_output")),
    #("call_id", json.string(function_call_output.call_id)),
    #("output", encode_output(function_call_output.output)),
  ]
  |> helpers.encode_option("id", function_call_output.id, json.string)
  |> helpers.encode_option("status", function_call_output.status, encode_status)
  |> json.object
}

pub fn default_function_call_output(
  call_id call_id: String,
  output output: Output,
) -> FunctionCallOutput {
  FunctionCallOutput(call_id:, output:, id: None, status: None)
}

pub fn function_call_output_id(
  config: FunctionCallOutput,
  id: String,
) -> FunctionCallOutput {
  FunctionCallOutput(..config, id: Some(id))
}

pub fn function_call_output_status(
  config: FunctionCallOutput,
  status: Status,
) -> FunctionCallOutput {
  FunctionCallOutput(..config, status: Some(status))
}

pub type Output {
  JsonString(String)
  InputTextContent(content.TextContent)
  InputImageContent(content.ImageContent)
  InputFileContent(content.FileContent)
}

fn encode_output(output: Output) {
  case output {
    JsonString(string) -> json.string(string)
    _ -> panic as "function.encode_output"
  }
}

// tools: ["function"]
/// ines a function in your own code the model can choose to call.
pub type Function {
  Function(
    // type: "function"
    /// The function's name (e.g. get_weather)
    name: String,
    /// Details on when and how to use the function
    description: Option(String),
    /// JSON schema defining the function's input arguments
    parameters: Json,
    /// Whether to enforce strict mode for the function call
    strict: Bool,
    /// Whether this tool should be loaded lazily by the model.
    defer_loading: Option(Bool),
  )
}

pub fn encode_function(function: Function) -> Json {
  [
    #("type", json.string("function")),
    #("name", json.string(function.name)),
    #("parameters", function.parameters),
    #("strict", json.bool(function.strict)),
  ]
  |> helpers.encode_option("description", function.description, json.string)
  |> helpers.encode_option("defer_loading", function.defer_loading, json.bool)
  |> json.object
}

pub fn decode_function() -> Decoder(Function) {
  use name <- decode.field("name", decode.string)
  use description <- decode.field("description", decode.optional(decode.string))
  // TODO: Fix parameters
  // use parameters <- decode.field("parameters", decode.string)
  use strict <- decode.field("strict", decode.bool)
  use defer_loading <- decode.optional_field(
    "defer_loading",
    None,
    decode.optional(decode.bool),
  )
  decode.success(Function(
    name:,
    description:,
    parameters: json.null(),
    strict:,
    defer_loading:,
  ))
}

pub fn new() -> Function {
  Function(
    name: "",
    description: None,
    parameters: json.null(),
    strict: False,
    defer_loading: None,
  )
}

pub fn name(function: Function, name: String) {
  Function(..function, name:)
}

pub fn description(function: Function, description: String) {
  Function(..function, description: Some(description))
}

pub fn parameters(function: Function, parameters: Json) {
  Function(..function, parameters:)
}

pub fn strict(function: Function, strict: Bool) {
  Function(..function, strict:)
}

pub fn defer_loading(function: Function, defer_loading: Bool) {
  Function(..function, defer_loading: Some(defer_loading))
}
