/// Allow the API to select a function 'horoscope' to return a user's horoscope
/// Demonstrates decoding only the previous response id and relevant function
/// calls needed to continue the conversation.
import gleam/dynamic/decode
import gleam/io
import gleam/json.{type Json}
import gleam/option.{type Option, None, Some}
import openai/client
import openai/error.{type OpenAIError}
import openai/responses
import openai/types/responses/content
import openai/types/responses/message
import openai/types/responses/response
import openai/types/responses/tool
import openai/types/responses/tool_choice
import openai/types/responses/tools/function
import openai/types/role

type Hop1Response {
  Hop1Response(id: String, calls: List(HoroscopeCall))
}

type HoroscopeCall {
  HoroscopeCall(call_id: String, arguments: String)
}

/// Requires `OPENAI_API_KEY` to be set in the environment.
pub fn main() -> Result(Nil, OpenAIError) {
  let assert Ok(client) = client.new()

  // 1. Define list of callable tools for the model
  let encode_parameters = fn() -> Json {
    json.object([
      #("type", json.string("object")),
      #(
        "properties",
        json.object([
          #(
            "sign",
            json.object([
              #("type", json.string("string")),
              #(
                "description",
                json.string("An astrological sign like Taurus or Aquarius"),
              ),
            ]),
          ),
        ]),
      ),
      #("required", json.array(["sign"], of: json.string)),
      #("additionalProperties", json.bool(False)),
    ])
  }

  let horoscope_tool =
    function.new()
    |> function.name("get_horoscope")
    |> function.parameters(encode_parameters())
    |> function.strict(True)
    |> function.description("Get today's horoscope for an astrological sign")
    |> tool.FunctionTool

  let get_horoscope = fn(sign: String) -> String {
    case sign {
      "{\"sign\":\"cancer\"}" | "{\"sign\":\"Cancer\"}" ->
        json.object([
          #("sign", json.string("Cancer")),
          #(
            "horoscope",
            json.string("Next Tuesday you will befriend a baby otter"),
          ),
        ])
      _ -> panic as sign
    }
    |> json.to_string()
  }

  // Build the initial user input for the first hop.
  let text = "What is my horoscope?  I am a Cancer"
  let hop1 = [
    message.new()
    |> message.with_role(role.User)
    |> message.with_content([
      content.new_text(text)
      |> content.TextContentItem,
    ])
    |> response.MessageItem,
  ]
  io.println("\nPrompt: " <> text)

  let request =
    responses.new()
    |> responses.with_model("gpt-5-mini")
    |> responses.with_input(response.Items(hop1))
    |> responses.with_tool_choice(tool_choice.options("required"))
    // Define the list of callable tools for the model
    |> responses.with_tools([horoscope_tool])

  // 2. Prompt the model with tools defined
  let assert Ok(hop1_response) =
    responses.create_with_decoder(client, request, decode_hop1_response())
  let function_call_output =
    hop1_response.calls
    |> map_horoscope_outputs(get_horoscope)
    |> response.Items

  let instructions = "Respond only with a horoscope generated by a tool."
  let request =
    responses.new()
    |> responses.with_model("gpt-5-mini")
    |> responses.with_instructions(instructions)
    |> responses.with_previous_response_id(hop1_response.id)
    |> responses.with_input(function_call_output)
    // Define the list of callable tools for the model
    |> responses.with_tools([horoscope_tool])

  let assert Ok(text) =
    responses.create_with_decoder(client, request, decode_output_message_text())
  io.println("Response: " <> text)
  Ok(Nil)
}

fn decode_hop1_response() -> decode.Decoder(Hop1Response) {
  use id <- decode.field("id", decode.string)
  use output <- decode.field(
    "output",
    decode.list(decode_horoscope_call_output_item()),
  )
  decode.success(Hop1Response(id:, calls: option.values(output)))
}

fn decode_horoscope_call_output_item() -> decode.Decoder(Option(HoroscopeCall)) {
  use type_ <- decode.field("type", decode.string)
  case type_ {
    "function_call" -> {
      use name <- decode.field("name", decode.string)
      case name {
        "get_horoscope" -> {
          use call_id <- decode.field("call_id", decode.string)
          use arguments <- decode.field("arguments", decode.string)
          decode.success(Some(HoroscopeCall(call_id:, arguments:)))
        }
        _ -> decode.success(None)
      }
    }
    _ -> decode.success(None)
  }
}

fn map_horoscope_outputs(
  calls: List(HoroscopeCall),
  get_horoscope: fn(String) -> String,
) -> List(response.InputOutput) {
  case calls {
    [HoroscopeCall(call_id:, arguments:), ..rest] -> [
      function.default_function_call_output(
        call_id:,
        output: function.JsonString(get_horoscope(arguments)),
      )
        |> response.FunctionCallOutputItem,
      ..map_horoscope_outputs(rest, get_horoscope)
    ]
    [] -> []
  }
}

fn decode_output_message_text() -> decode.Decoder(String) {
  use outputs <- decode.field("output", decode.list(decode_output_item_text()))
  case option.values(outputs) {
    [text, ..] -> decode.success(text)
    [] -> decode.failure("", expected: "message output text")
  }
}

fn decode_output_item_text() -> decode.Decoder(Option(String)) {
  use type_ <- decode.field("type", decode.string)
  case type_ {
    "message" ->
      decode.at(["content"], decode.at([0], decode.at(["text"], decode.string)))
      |> decode.map(Some)
    _ -> decode.success(None)
  }
}
