/// Allow the API to select a function 'horoscope' to return a user's horoscope
/// TODO: Should some of this data wrangling go into the responses.gleam code?
import gleam/io
import gleam/json.{type Json}
import gleam/list
import openai/client
import openai/error.{type OpenAIError}
import openai/responses
import openai/types/responses/content
import openai/types/responses/message
import openai/types/responses/response.{type InputOutput, type Response}
import openai/types/responses/tool
import openai/types/responses/tool_choice
import openai/types/responses/tools/function
import openai/types/role

/// Requires `OPENAI_API_KEY` to be set in the environment.
pub fn main() -> Result(Response, OpenAIError) {
  let assert Ok(client) = client.new()

  // 1. Define list of callable tools for the model
  let encode_parameters = fn() -> Json {
    json.object([
      #("type", json.string("object")),
      #(
        "properties",
        json.object([
          #(
            "sign",
            json.object([
              #("type", json.string("string")),
              #(
                "description",
                json.string("An astrological sign like Taurus or Aquarius"),
              ),
            ]),
          ),
        ]),
      ),
      #("required", json.array(["sign"], of: json.string)),
      #("additionalProperties", json.bool(False)),
    ])
  }

  let horoscope_tool =
    function.new()
    |> function.name("get_horoscope")
    |> function.parameters(encode_parameters())
    |> function.strict(True)
    |> function.description("Get today's horoscope for an astrological sign")
    |> tool.FunctionTool

  let get_horoscope = fn(sign: String) -> String {
    case sign {
      "{\"sign\":\"cancer\"}" | "{\"sign\":\"Cancer\"}" ->
        json.object([
          #("sign", json.string("Cancer")),
          #(
            "horoscope",
            json.string("Next Tuesday you will befriend a baby otter"),
          ),
        ])
      _ -> panic as sign
    }
    |> json.to_string()
  }

  // Create a running input list we will add over time
  let text = "What is my horoscope?  I am a Cancer"
  let hop1 = [
    message.new()
    |> message.with_role(role.User)
    |> message.with_content([
      content.new_text(text)
      |> content.TextContentItem,
    ])
    |> response.MessageItem,
  ]
  io.println("\nPrompt: " <> text)

  let request =
    responses.new()
    |> responses.with_model("gpt-5-mini")
    |> responses.with_input(response.Items(hop1))
    |> responses.with_tool_choice(tool_choice.options("required"))
    // Define the list of callable tools for the model
    |> responses.with_tools([horoscope_tool])

  // 2. Prompt the model with tools defined
  let assert Ok(response) = responses.create(client, request)
  // echo response.output

  // TODO Should this merging of input and output go into
  // `responses.gleam`
  // Importantly [hop1, reasoning, fn_call1, fn_call2, out1, out2]

  let input_list = list.append(hop1, response.output)
  let function_call_output =
    list.fold(response.output, [], fn(acc, item: InputOutput) {
      case item {
        response.FunctionCallItem(function.FunctionCall(
          name:,
          arguments:,
          call_id:,
          ..,
        )) ->
          case name {
            "get_horoscope" -> {
              let output = get_horoscope(arguments)

              let fco =
                function.default_function_call_output(
                  call_id:,
                  output: function.JsonString(output),
                )
                |> response.FunctionCallOutputItem
              list.append(acc, [fco])
            }
            _ -> acc
          }
        _ -> acc
      }
    })
  let hop2 = list.append(input_list, function_call_output) |> response.Items

  let instructions = "Respond only with a horoscope generated by a tool."
  let request =
    responses.new()
    |> responses.with_model("gpt-5-mini")
    |> responses.with_instructions(instructions)
    |> responses.with_input(hop2)
    // Define the list of callable tools for the model
    |> responses.with_tools([horoscope_tool])

  let assert Ok(response) = responses.create(client, request)
  let assert [
    response.ResponseOutputMessageItem(message.ResponseOutputMessage(
      content:,
      ..,
    )),
    ..
  ] = response.output
  let assert [message.OutputTextItem(message.OutputText(text:, ..)), ..] =
    content
  io.println("Response: " <> text)
  Ok(response)
}
