// https://platform.openai.com/docs/api-reference/chat
//
import gleam/dynamic/decode
import gleam/option.{type Option, None, Some}
import openai/types/role

const default_model = "gpt-5.2"

pub type CompletionCreateParams {
  CompletionCreateParams(
    /// The model to use for the chat completion.
    model: String,
    /// What sampling temperature to use.
    temperature: Float,
    /// Whether to stream the chat completion response.
    stream: Bool,
  )
}

pub fn new() -> CompletionCreateParams {
  CompletionCreateParams(model: default_model, temperature: 0.7, stream: False)
}

pub fn with_model(
  config: CompletionCreateParams,
  model: String,
) -> CompletionCreateParams {
  CompletionCreateParams(..config, model: model)
}

pub fn with_temperature(
  config: CompletionCreateParams,
  temperature: Float,
) -> CompletionCreateParams {
  CompletionCreateParams(..config, temperature: temperature)
}

pub fn with_stream(
  config: CompletionCreateParams,
  stream: Bool,
) -> CompletionCreateParams {
  CompletionCreateParams(..config, stream: stream)
}

// Audio
pub type Audio {
  Audio(data: String, expires_at: Int, id: String, transcript: String)
}

fn decode_audio() {
  use data <- decode.field("data", decode.string)
  use expires_at <- decode.field("expires_at", decode.int)
  use id <- decode.field("id", decode.string)
  use transcript <- decode.field("transcript", decode.string)
  decode.success(Some(Audio(data:, expires_at:, id:, transcript:)))
}

pub type UrlCitation {
  UrlCitation(end_index: Int, start_index: Int, title: String, url: String)
}

fn decode_url_citation_type() {
  use end_index <- decode.field("end_index", decode.int)
  use start_index <- decode.field("start_index", decode.int)
  use title <- decode.field("title", decode.string)
  use url <- decode.field("url", decode.string)
  decode.success(UrlCitation(end_index:, start_index:, title:, url:))
}

pub type Annotation {
  Annotation(type_: String, url_citation: UrlCitation)
}

fn decode_annotation() {
  use type_ <- decode.field("type", decode.string)
  use url_citation <- decode.field("url_citation", decode_url_citation_type())
  decode.success(Annotation(type_:, url_citation:))
}

pub type Function {
  Function(arguments: String, name: String)
}

fn decode_function() {
  use arguments <- decode.field("arguments", decode.string)
  use name <- decode.field("name", decode.string)
  decode.success(Function(arguments:, name:))
}

pub type ToolCall {
  ToolCall(function: Function, id: String, type_: String)
}

fn decode_tool_call() {
  use function <- decode.field("function", decode_function())
  use id <- decode.field("id", decode.string)
  use type_ <- decode.field("type", decode.string)
  decode.success(ToolCall(function:, id:, type_:))
}

// Message object in a choice
pub type Message {
  Message(
    /// The role of the author of this message.
    role: role.Role,
    /// The contents of the message.
    content: String,
    /// Tool calls generated by the model.
    tool_calls: Option(List(ToolCall)),
    /// The refusal message generated by the model.
    refusal: Option(String),
    /// Annotations for the message.
    annotations: List(Annotation),
    /// Audio output metadata for the message.
    audio: Option(Audio),
  )
}

fn decode_message() {
  let tool_calls_decoder = decode.optional(decode.list(decode_tool_call()))
  use role <- decode.field("role", role.decode_role())
  use content <- decode.optional_field("content", "", decode.string)
  use refusal <- decode.optional_field(
    "refusal",
    None,
    decode.optional(decode.string),
  )
  use audio <- decode.optional_field("audio", None, decode_audio())
  use annotations <- decode.optional_field(
    "annotations",
    [],
    decode.list(decode_annotation()),
  )
  use tool_calls <- decode.optional_field(
    "tool_calls",
    None,
    tool_calls_decoder,
  )
  decode.success(Message(
    role:,
    content:,
    refusal:,
    annotations:,
    audio:,
    tool_calls:,
  ))
}

pub type Messages =
  List(Message)

pub type BytesLogprobToken {
  BytesLogprobToken(
    /// A list of integers representing the UTF-8 bytes of the token.
    bytes: Option(List(Int)),
    /// The log probability of this token.
    logprob: Float,
    /// The token.
    token: String,
  )
}

fn decode_bytes_logprob_token() {
  use bytes <- decode.field("bytes", decode.optional(decode.list(decode.int)))
  use logprob <- decode.field("logprob", decode.float)
  use token <- decode.field("token", decode.string)
  decode.success(BytesLogprobToken(bytes:, logprob:, token:))
}

pub type Content {
  Content(
    /// A list of integers representing the UTF-8 bytes of the token.
    bytes: Option(List(Int)),
    /// The log probability of this token.
    logprob: Float,
    /// The token.
    token: String,
    /// The most likely tokens and their log probabilities at this position.
    top_logprobs: List(BytesLogprobToken),
  )
}

fn decode_content() {
  use bytes <- decode.field("bytes", decode.optional(decode.list(decode.int)))
  use logprob <- decode.field("logprob", decode.float)
  use token <- decode.field("token", decode.string)
  use top_logprobs <- decode.field(
    "top_logprobs",
    decode.list(decode_bytes_logprob_token()),
  )
  decode.success(Content(bytes:, logprob:, token:, top_logprobs:))
}

pub type Refusal {
  Refusal(
    /// A list of integers representing the UTF-8 bytes of the token.
    bytes: Option(List(Int)),
    /// The log probability of this token.
    logprob: Float,
    /// The token.
    token: String,
    /// The most likely tokens and their log probabilities at this position.
    top_logprobs: List(BytesLogprobToken),
  )
}

fn decode_refusal() {
  use bytes <- decode.field("bytes", decode.optional(decode.list(decode.int)))
  use logprob <- decode.field("logprob", decode.float)
  use token <- decode.field("token", decode.string)
  use top_logprobs <- decode.field(
    "top_logprobs",
    decode.list(decode_bytes_logprob_token()),
  )
  decode.success(Refusal(bytes:, logprob:, token:, top_logprobs:))
}

pub type Logprobs {
  Logprob(content: List(Content), refusal: List(Refusal))
}

fn decode_logprobs() {
  use content <- decode.field("content", decode.list(decode_content()))
  use refusal <- decode.field("refusal", decode.list(decode_refusal()))
  decode.success(Logprob(content:, refusal:))
}

// One result choice from the completions
pub type CompletionChoice {
  CompletionChoice(
    /// The index of the choice in the list of choices.
    index: Int,
    /// The chat completion message generated by the model.
    message: Message,
    /// The reason the model stopped generating tokens.
    finish_reason: Option(String),
    /// Log probability information for the choice.
    logprobs: Option(Logprobs),
  )
}

fn decode_completion_choice() {
  use finish_reason <- decode.optional_field(
    "finish_reason",
    None,
    decode.optional(decode.string),
  )
  use index <- decode.field("index", decode.int)
  use logprobs <- decode.optional_field(
    "logprobs",
    None,
    decode.optional(decode_logprobs()),
  )
  use message <- decode.field("message", decode_message())
  decode.success(CompletionChoice(index:, message:, finish_reason:, logprobs:))
}

pub type CompletionTokenDetails {
  CompletionTokenDetails(
    /// The number of tokens accepted from prediction.
    accepted_prediction_tokens: Int,
    /// The number of audio tokens in the completion.
    audio_tokens: Int,
    /// The number of reasoning tokens in the completion.
    reasoning_tokens: Int,
    /// The number of tokens rejected from prediction.
    rejected_prediction_tokens: Int,
  )
}

fn decode_completion_tokens_details() {
  use accepted_prediction_tokens <- decode.optional_field(
    "accepted_prediction_tokens",
    0,
    decode.int,
  )
  use audio_tokens <- decode.optional_field("audio_tokens", 0, decode.int)
  use reasoning_tokens <- decode.optional_field(
    "reasoning_tokens",
    0,
    decode.int,
  )
  use rejected_prediction_tokens <- decode.optional_field(
    "rejected_prediction_tokens",
    0,
    decode.int,
  )
  decode.success(CompletionTokenDetails(
    accepted_prediction_tokens:,
    audio_tokens:,
    reasoning_tokens:,
    rejected_prediction_tokens:,
  ))
}

pub type PromptTokenDetails {
  PromptTokenDetails(cached_tokens: Int, audio_tokens: Int)
}

fn decode_prompt_tokens_details() {
  use cached_tokens <- decode.optional_field("cached_tokens", 0, decode.int)
  use audio_tokens <- decode.optional_field("audio_tokens", 0, decode.int)
  decode.success(PromptTokenDetails(cached_tokens:, audio_tokens:))
}

// Usage breakdown
pub type Usage {
  Usage(
    /// The number of prompt tokens.
    prompt_tokens: Int,
    /// The number of completion tokens.
    completion_tokens: Int,
    /// The total number of tokens used.
    total_tokens: Int,
    /// A detailed breakdown of completion tokens.
    completion_tokens_details: CompletionTokenDetails,
    /// A detailed breakdown of prompt tokens.
    prompt_tokens_details: PromptTokenDetails,
  )
}

fn decode_usage() {
  use completion_tokens <- decode.field("completion_tokens", decode.int)
  use prompt_tokens <- decode.field("prompt_tokens", decode.int)
  use total_tokens <- decode.field("total_tokens", decode.int)
  use prompt_tokens_details <- decode.optional_field(
    "prompt_tokens_details",
    PromptTokenDetails(cached_tokens: 0, audio_tokens: 0),
    decode_prompt_tokens_details(),
  )
  use completion_tokens_details <- decode.optional_field(
    "completion_tokens_details",
    CompletionTokenDetails(
      accepted_prediction_tokens: 0,
      audio_tokens: 0,
      reasoning_tokens: 0,
      rejected_prediction_tokens: 0,
    ),
    decode_completion_tokens_details(),
  )
  decode.success(Usage(
    prompt_tokens:,
    completion_tokens:,
    total_tokens:,
    completion_tokens_details:,
    prompt_tokens_details:,
  ))
}

// Full response from OpenAI /v1/chat/completions
pub type ChatCompletion {
  ChatCompletion(
    /// A unique identifier for the chat completion.
    id: String,
    /// The object type, which is always chat.completion.
    object: String,
    /// The Unix timestamp for when the completion was created.
    created: Int,
    /// The model used for the chat completion.
    model: String,
    /// A list of chat completion choices.
    choices: List(CompletionChoice),
    /// Usage statistics for the completion request.
    usage: Usage,
    /// The service tier used to process the request.
    service_tier: String,
    /// The backend configuration fingerprint for the request.
    system_fingerprint: Option(String),
  )
}

pub fn decode_chat_completion() {
  use id <- decode.field("id", decode.string)
  use object <- decode.field("object", decode.string)
  use created <- decode.field("created", decode.int)
  use choices <- decode.field(
    "choices",
    decode.list(decode_completion_choice()),
  )
  use usage <- decode.field("usage", decode_usage())
  use model <- decode.field("model", decode.string)
  use service_tier <- decode.optional_field(
    "service_tier",
    "default",
    decode.string,
  )
  use system_fingerprint <- decode.optional_field(
    "system_fingerprint",
    None,
    decode.optional(decode.string),
  )
  decode.success(ChatCompletion(
    choices:,
    id:,
    object:,
    created:,
    model:,
    service_tier:,
    system_fingerprint:,
    usage:,
  ))
}

// region:    ---  streamed response from OpenAI /v1/chat/completions
pub type Delta {
  Delta(role: String, content: String)
}

fn decode_delta() {
  // use finish_reason <- decode.field("finish_reason", decode.string)
  use role <- decode.optional_field("role", "assistant", decode.string)
  use content <- decode.optional_field("content", "", decode.string)
  decode.success(Delta(content:, role:))
}

pub type CompletionChoiceChunk {
  CompletionChoiceChunk(
    /// The index of the choice in the list of streamed choices.
    index: Int,
    /// The incremental delta emitted for this choice.
    delta: Delta,
    /// Log probability information for the streamed choice.
    logprobs: Option(Logprobs),
    /// The reason the model stopped generating tokens.
    finish_reason: Option(String),
  )
}

fn decode_completion_choice_chunk() {
  // use finish_reason <- decode.field("finish_reason", decode.string)
  use index <- decode.field("index", decode.int)
  use delta <- decode.field("delta", decode_delta())
  use logprobs <- decode.optional_field(
    "logprobs",
    None,
    decode.optional(decode_logprobs()),
  )
  use finish_reason <- decode.field(
    "finish_reason",
    decode.optional(decode.string),
  )
  decode.success(CompletionChoiceChunk(
    index:,
    delta:,
    logprobs:,
    finish_reason:,
  ))
}

pub type CompletionChunk {
  CompletionChunk(
    /// A unique identifier for the chat completion chunk.
    id: String,
    /// The object type, which is always chat.completion.chunk.
    object: String,
    /// The Unix timestamp for when the chunk was created.
    created: Int,
    /// The model used for the chat completion.
    model: String,
    /// A list of streamed chat completion choices.
    choices: List(CompletionChoiceChunk),
    /// The service tier used to process the request.
    service_tier: Option(String),
    /// The backend configuration fingerprint for the request.
    system_fingerprint: Option(String),
    /// Obfuscation content included on streaming events.
    obfuscation: Option(String),
  )
}

pub fn decode_completion_chunk() {
  use id <- decode.field("id", decode.string)
  use object <- decode.field("object", decode.string)
  use created <- decode.field("created", decode.int)
  use model <- decode.field("model", decode.string)
  use service_tier <- decode.optional_field(
    "service_tier",
    None,
    decode.optional(decode.string),
  )
  use choices <- decode.field(
    "choices",
    decode.list(decode_completion_choice_chunk()),
  )
  use obfuscation <- decode.optional_field(
    "obfuscation",
    None,
    decode.optional(decode.string),
  )
  use system_fingerprint <- decode.field(
    "system_fingerprint",
    decode.optional(decode.string),
  )
  decode.success(CompletionChunk(
    choices:,
    id:,
    object:,
    created:,
    model:,
    service_tier:,
    system_fingerprint:,
    obfuscation:,
  ))
}
// endregion: ---  streamed response from OpenAI /v1/chat/completions
